### ISSUE TITLE
Not able to build on Swift 4.1

### ISSUE THREAD

**Issue by samuelyang** [robbiehanson/XMPPFramework#1075]
I tried to use your framework in Xcode 9.4 and Swift 4.1, build failed with below compilation errors:
Semantic Issue Group
/Pods/KissXML/KissXML/DDXMLDocument.m:92:2: Implicit declaration of function 'xmlKeepBlanksDefault' is invalid in C99
/Pods/KissXML/KissXML/DDXMLDocument.m:94:18: Implicit declaration of function 'xmlParseMemory' is invalid in C99
/Pods/KissXML/KissXML/DDXMLDocument.m:94:18: Conflicting types for 'xmlParseMemory'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/include/libxml2/libxml/parser.h:846:3: Previous declaration is here
Modules Issue Group
/Pods/KissXML/KissXML/DDXMLDocument.m:92:2: Declaration of 'xmlKeepBlanksDefault' must be imported from module 'libxml2.parser' before it is required
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/include/libxml2/libxml/parser.h:852:3: Previous declaration is here
/Pods/KissXML/KissXML/DDXMLDocument.m:94:18: Declaration of 'xmlParseMemory' must be imported from module 'libxml2.parser' before it is required

Could you please take a quick look? Hope there's a quick fix:)
