### ISSUE TITLE
Unable to compile in Xcode 8.0: Redefinition of module "dnssd"

### ISSUE THREAD

**Issue by AntonioPozo** [robbiehanson/XMPPFramework#810]
I just upgraded to Xcode 8 and have the following build error:
![module_modulemap](https://cloud.githubusercontent.com/assets/11032684/19033695/0eda8bf0-8960-11e6-9fb6-29d8ed9a990d.png)
 
Any suggestions?
Thanks!

**Comment by davidloveengles** [comment]
I have this issues too, do you  resolve？

**Comment by changDL** [comment]
It's really a big problem.

**Comment by chrisballinger** [comment]
modulemaps are no longer used anywhere in XMPPFramework or its dependencies. Use the master branch.
