### ISSUE TITLE
Unable To Compile Using Xcode 7.3 (beta)

### ISSUE THREAD

**Issue by ZbadhabitZ** [robbiehanson/XMPPFramework#686]
I know it's still in beta, but I've been prepping a project for release with iOS 9.3, and am having trouble compiling XMPPFramework.  I've started a new project and installed XMPPFramework via CocoaPods.  The following errors occur when compiling;

![screen shot 2016-02-25 at 7 29 51 am](https://cloud.githubusercontent.com/assets/17473851/13319703/9f145e62-db91-11e5-8be1-abd99641be62.png)

**XMPPFramework**
**module.modulemap**
_Redefinition of module 'Compression'_
_Redefinition of module 'Darwin'_
_Redefinition of module 'os'_
_Redefinition of module 'libkern'_
**dns_sd.h**
_Could not find module 'Darwin'_
**XMPPSRVResolver.h**
_Could not build module 'dnssdSimu'

I recognize that some of these errors may be due to other dependencies, but was curious if anyone had any suggestions to stay ahead of the iOS release game.  Thanks!

**Comment by brandenbyers** [comment]
Same issue, different errors. XMPPFramework is the only build failure that I get in Xcode Version 7.3 beta (7D162j).

<img width="254" alt="screen shot 2016-03-09 at 9 19 48 am" src="https://cloud.githubusercontent.com/assets/7098232/13643952/3a84aac8-e5d8-11e5-8716-b3510e1e0aba.png">

**Comment by brandenbyers** [comment]
Renaming Xcode-beta to "Xcode" fixed the errors I was receiving previously. XMPPFramework uses hardcoded values, so doesn't play nice with the beta name.

**Comment by JoeFerrucci** [comment]
This is still an issue. 
<img width="264" alt="screen shot 2016-04-05 at 9 10 22 pm" src="https://cloud.githubusercontent.com/assets/2114494/14305769/9b3dba60-fb74-11e5-944d-20936628188e.png">

I have tried:
Clean Build.
Deleted Derived Data.
Remove /Pods and Podfile.lock
Ran pod update
Ran pod install
Made sure my command-line tools are up to date.

This is a complete fresh install of OS X El Capitan and Xcode 7.3
This issue also took place on an updated version Xcode 7.2.1 -> 7.3 

Both systems experienced the issue. 

Haven't figured it out, yet.

**Comment by JoeFerrucci** [comment]
FYI, I was attempting all of that while trying to build to an iPhone Simulator. 

Once I switched to build to an actual device the errors went away and I was able to build successfully.

**Comment by JoeFerrucci** [comment]
UPDATE, FIXED:

I ended up finding the problem. In `Utilities/XMPPSRVResolver.h` 

Changed from this:
```
#if !(TARGET_IPHONE_SIMULATOR)
#import <dns_sd.h>
#else
#import <dns_sd.h>
#endif
```

To this:
```
#if !(TARGET_IPHONE_SIMULATOR)
@import dnssd;
#else
@import dnssdSimu;
#endif
```

Builds successfully to Simulators AND real iPhone devices. Whereas before it would only build to a real device and not to simulators.

**Comment by chrisballinger** [comment]
This is what's on the current master branch. Not sure how it got the other way in your branch

**Comment by SureshShakthi** [comment]
Anyone found the solution?
