### ISSUE TITLE
Redefinition of module 'dnssd' when upgrading xcode to 8.0 and build my project

### ISSUE THREAD

**Issue by itollei** [robbiehanson/XMPPFramework#804]
i found this issue when upgrading xcode to 8.0, then i build my project, throw this error:Redefinition of module 'dnssd'.
Module:KissXML
File:module.modulemap
Xcode:8.0

how can i solve this issue? 
thanks,

leo.pan

**Comment by marioacarvalho** [comment]
Also here!

**Comment by Mqhong** [comment]
redefinition of module 'dnssd' previously defined here~ ,we need help

**Comment by x3mall1986** [comment]
In this thread fix 
https://github.com/robbiehanson/XMPPFramework/issues/800

**Comment by juxiaohui** [comment]
Also here!

**Comment by Mqhong** [comment]
Thanks

**Comment by AntonioPozo** [comment]
module libxml [system] {
	header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/libxml2/libxml/tree.h"
	export *
}

module libxmlSimu [system] {
	header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2/libxml/tree.h"
	export *
}

module dnssd_x [system] {
	header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/dns_sd.h"
	export *
}

module dnssdSimu_x [system] {
	header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/dns_sd.h"
	export *
}

this is the content of my module.modulemap file. It´s works for me

**Comment by agustinem** [comment]
Antonio Pozo is our leader
